### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yxik08** [yejue/genshin-lyre-assistant#1]

**Comment by yejue** [comment]
？什么报错

**Comment by yxik08** [comment]
Exception ignored in thread started by: <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x00000291AE22BB50>>
Traceback (most recent call last):
  File "C:\Users\By\AppData\Local\Programs\Python\Python310\lib\site-packages\system_hotkey\util.py", line 37, in call_functions
    func(*args, **kwargs)
  File "C:\Users\By\AppData\Local\Programs\Python\Python310\lib\site-packages\system_hotkey\system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by yejue** [comment]
这个问题应该是 python 版本差异，里面有些模块放的位置变了。关于这点我目前只使用了 python3.8 版本。其余版本暂时不想适配.....
